-- EventBok Concert Ticket Booking System
-- Database Schema

DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS tickets CASCADE;
DROP TABLE IF EXISTS concert_zone_prices CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS seats CASCADE;
DROP TABLE IF EXISTS zones CASCADE;
DROP TABLE IF EXISTS seatmaps CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS concerts CASCADE;
DROP TABLE IF EXISTS venues CASCADE;
DROP TABLE IF EXISTS organizers CASCADE;
DROP TABLE IF EXISTS customers CASCADE;

-- Organizers
CREATE TABLE organizers (
  organizer_id   BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  organizer_name VARCHAR(100) NOT NULL,
  contact_email  VARCHAR(100) NOT NULL UNIQUE,
  phone_number   VARCHAR(20)  NOT NULL,
  created_at     TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- Venues — capacity_template drives which seat layout is generated
CREATE TABLE venues (
  venue_id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  venue_name         VARCHAR(100) NOT NULL,
  location           VARCHAR(200) NOT NULL,
  capacity           INT          NOT NULL CHECK (capacity > 0),
  capacity_template  INT          NOT NULL DEFAULT 500
                     CHECK (capacity_template IN (500, 2000, 5000))
);

-- Concerts
CREATE TABLE concerts (
  concert_id   BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  concert_name VARCHAR(100) NOT NULL,
  artist_name  VARCHAR(100) NOT NULL,
  description  TEXT,
  organizer_id BIGINT       NOT NULL REFERENCES organizers(organizer_id) ON DELETE RESTRICT,
  venue_id     BIGINT       NOT NULL REFERENCES venues(venue_id) ON DELETE RESTRICT,
  status       VARCHAR(20)  NOT NULL DEFAULT 'upcoming'
               CHECK (status IN ('upcoming','ongoing','completed','cancelled')),
  cover_url    VARCHAR(500),
  created_at   TIMESTAMP    NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- SeatMaps — one per venue, generated from the venue's capacity_template
CREATE TABLE seatmaps (
  seatmap_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  map_name   VARCHAR(100) NOT NULL,
  template   VARCHAR(50)  NOT NULL DEFAULT 'concert_hall'
             CHECK (template IN ('concert_hall', 'arena_stadium', 'amphitheater')),
  venue_id   BIGINT       NOT NULL REFERENCES venues(venue_id) ON DELETE CASCADE
);

-- Zones — belong to a seatmap (venue-level), zone prices are overridden per concert
CREATE TABLE zones (
  zone_id    BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  zone_name  VARCHAR(50)   NOT NULL,
  type       VARCHAR(20)   NOT NULL DEFAULT 'regular'
             CHECK (type IN ('vip', 'premium', 'regular')),
  color      VARCHAR(30),
  price      DECIMAL(10,2) NOT NULL CHECK (price >= 0),  -- default / reference price
  capacity   INT           NOT NULL CHECK (capacity > 0),
  rows       TEXT[],
  seatmap_id BIGINT        NOT NULL REFERENCES seatmaps(seatmap_id) ON DELETE CASCADE
);

-- Seats — physical seats per zone (shared across concerts at same venue)
CREATE TABLE seats (
  seat_id     BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  seat_no     VARCHAR(10) NOT NULL,
  seat_status VARCHAR(20) NOT NULL DEFAULT 'available'
              CHECK (seat_status IN ('available', 'reserved', 'booked')),
  zone_id     BIGINT      NOT NULL REFERENCES zones(zone_id) ON DELETE CASCADE
);

-- Sessions
CREATE TABLE sessions (
  session_id   BIGINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  session_name VARCHAR(100) NOT NULL,
  show_date    DATE         NOT NULL,
  start_time   TIME         NOT NULL,
  end_time     TIME         NOT NULL,
  concert_id   BIGINT       NOT NULL REFERENCES concerts(concert_id) ON DELETE CASCADE,
  venue_id     BIGINT       NOT NULL REFERENCES venues(venue_id) ON DELETE RESTRICT
);

-- Concert-specific zone pricing (overrides zone.price for a given concert)
CREATE TABLE concert_zone_prices (
  id         BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  concert_id BIGINT        NOT NULL REFERENCES concerts(concert_id) ON DELETE CASCADE,
  zone_id    BIGINT        NOT NULL REFERENCES zones(zone_id) ON DELETE CASCADE,
  price      DECIMAL(10,2) NOT NULL CHECK (price >= 0),
  UNIQUE (concert_id, zone_id)
);

-- Customers
CREATE TABLE customers (
  customer_id   BIGINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  firstname     VARCHAR(50)  NOT NULL,
  lastname      VARCHAR(50)  NOT NULL,
  email         VARCHAR(100) NOT NULL UNIQUE,
  phone         VARCHAR(20)  NOT NULL UNIQUE,
  address       VARCHAR(200),
  date_of_birth DATE         NOT NULL,
  register_date DATE         NOT NULL DEFAULT CURRENT_DATE
);

-- Bookings
CREATE TABLE bookings (
  booking_id   BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  booking_date TIMESTAMP   NOT NULL DEFAULT NOW(),
  status       VARCHAR(20) NOT NULL DEFAULT 'pending'
               CHECK (status IN ('pending', 'confirmed', 'cancelled')),
  customer_id  BIGINT      NOT NULL REFERENCES customers(customer_id) ON DELETE RESTRICT,
  session_id   BIGINT      NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT
);

-- Tickets
CREATE TABLE tickets (
  ticket_id         BIGINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ticket_type       VARCHAR(50)  NOT NULL,
  qr_code           VARCHAR(100) NOT NULL UNIQUE,
  redemption_status VARCHAR(20)  NOT NULL DEFAULT 'not_redeemed'
                    CHECK (redemption_status IN ('not_redeemed', 'redeemed', 'expired')),
  booking_id  BIGINT NOT NULL REFERENCES bookings(booking_id) ON DELETE CASCADE,
  seat_id     BIGINT NOT NULL REFERENCES seats(seat_id) ON DELETE RESTRICT,
  session_id  BIGINT NOT NULL REFERENCES sessions(session_id) ON DELETE RESTRICT,
  UNIQUE (seat_id, session_id)
);

-- Payments
CREATE TABLE payments (
  payment_id     BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  payment_date   TIMESTAMP     NOT NULL DEFAULT NOW(),
  total_price    DECIMAL(10,2) NOT NULL CHECK (total_price >= 0),
  payment_method VARCHAR(50)   NOT NULL
                 CHECK (payment_method IN ('credit_card', 'debit_card', 'bank_transfer', 'qr_code')),
  payment_status VARCHAR(20)   NOT NULL DEFAULT 'pending'
                 CHECK (payment_status IN ('pending', 'completed', 'failed', 'refunded')),
  transaction_id VARCHAR(100),
  booking_id     BIGINT        NOT NULL UNIQUE REFERENCES bookings(booking_id) ON DELETE RESTRICT
);
